import { useContext, useEffect } from 'react'
import Head from 'next/head'

// Components
import NavBar from '../components/NavBar/NavBar'
import SideBar from '../components/SideBar/SideBar'
import MarkDown from '../components/MarkDown/MarkDown'
import DeleteModal from '../components/DeleteModal/DeleteModal'

// Context
import { AppContext } from '../contexts/AppContext'
import { DataContext } from '../contexts/DataContext'

// Fonts
import { Roboto } from '@next/font/google'

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    style: ['normal'],
    variable: '--roboto-font',
})

// Styles
import styles from './index.module.scss'

export default function Home() {
    const { showMenu } = useContext(AppContext)
    const { deleteDocument } = useContext(DataContext)

    useEffect(() => {
        // We listen to the resize event
        window.addEventListener('resize', () => {
            // We execute the same script as before
            let vh = window.innerHeight * 0.01
            document.documentElement.style.setProperty('--vh', `${vh}px`)
        })
    }, [])

    return (
        <>
            <Head>
                <title>In-Browser Markdown Editor</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className={`${styles.appWrapper} ${roboto.variable}`}>
                {showMenu && <SideBar />}
                <div className={styles.appContainer}>
                    <NavBar />
                    <MarkDown />
                    {deleteDocument && <DeleteModal />}
                </div>
            </div>
        </>
    )
}
